version: "3.0"

services:
  user_db:
    image: mongo:latest
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "27018:27017"
    volumes:
      - user_db:/data/db

  user_service:
    depends_on:
      - user_db
    build:
      context: ./data_services/user_service
    restart: always
    env_file: ./.env
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    ports:
      - "80:8080"
    stdin_open: true
    tty: true

volumes:
  user_db:
