version: "3.0"

services:
  user_db:
    image: mongo:latest
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USER_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$USER_DB_PASSWORD
    ports:
      - "27018:27017"
    volumes:
      - user_db:/data/db

  user_service:
    depends_on:
      - user_db
    build:
      context: ./data_services/user_service
    restart: always
    env_file: ./.env
    environment:
      - DB_HOST=$USER_DB_HOST
      - DB_USER=$USER_DB_USER
      - DB_PASSWORD=$USER_DB_PASSWORD
      - DB_NAME=$USER_DB_NAME
      - DB_PORT=$USER_DB_PORT
    ports:
      - "80:8080"
    stdin_open: true
    tty: true

  nominatim_adapter:
    build:
      context: ./adapter_services/nominatim_adapter
    restart: always
    env_file: ./.env
    ports:
      - "8082:5000"
    stdin_open: true
    tty: true

  openweather_adapter:
    build:
      context: ./adapter_services/openweather_adapter
    restart: always
    env_file: ./.env
    environment:
      - OPENWEATHER_API_KEY=$OPENWEATHER_API_KEY
    ports:
      - "8083:8080"
    stdin_open: true
    tty: true

volumes:
  user_db:
